### ISSUE TITLE
Feature: lazy load models and types

### ISSUE THREAD

**Issue by yanyongyu** [yanyongyu/githubkit#11]

**Comment by dosisod** [comment]
Hi! I've noticed that importing githubkit takes about a 1-1.5 seconds on my machine due to all the pydantic models that need to be parsed. Is this what this issue is talking about? If it is, I wouldn't mind looking into it (the slow import times take up a good chunk of my test suite).

**Comment by yanyongyu** [comment]
GitHub REST API now supports versioning, models may be generated for every version to support this. So, we should find a way to load models only when we using them, including rest api and webhooks.

**Comment by dosisod** [comment]
If the type checking code is only needed in a `TYPE_CHECKING` context, then it sounds like an easy win to just move it into an `if` statement.

With the lazy loading side of things, there are lots of different ways you could go about importing the models, depending on how granular you want things to be. Some of the approaches I can think of:

1. Load everything once one model is used. This means we still have to load all the models, except now we just delay the loading until later (probably not ideal)
2. Load REST/Webhook models when used. If you don't use REST (or Webhooks), then you shouldn't need to pay for both. Still, if you are only calling a few endpoints, loading all the REST models is slow
3. Load models that are in the same "group". For example, when calling a user endpoint, load all the user models. This might require some extra work, but would require much less importing (assuming you're only use a portion of the GitHub API at any given point in time).
4. Load each model as-needed. This is probably overkill, but essentially we would only load the specific models needed to call the endpoints we need, nothing more. This sounds like a lot more work for little benefit.

Each one of these have their pros and cons. I would say the more granular the better, though per-model importing is probably too-granular to be useful.

**Comment by dosisod** [comment]
As for API versioning, that will be it's own set of issues regardless of whether lazy loading is implemented or not. I would say lazy loading should be implemented before API versioning, otherwise we will be parsing multiple different versioned APIs, further compounding the loading time issue. Also, there only seems to be one API version that GitHub supports at the moment, version `2022-11-28`. I don't know when they will be coming out with a new version, but for now it seems like we only need to support the current version, is that correct?

Also, how will API versioning work with the type information? I assume we would need different types and classes for each API version, or somehow find a way to share the core logic between the different API versions.
