### ISSUE TITLE
Should `Missing` type implicitly allow `None`?

### ISSUE THREAD

**Issue by frankie567** [yanyongyu/githubkit#47]
GitHub API schema is not always consistent with the required and nullable fields. Currently, this is solved by maintaining the [`schema_overrides` table](https://github.com/yanyongyu/githubkit/blob/fd80590ffd0efbed97398421f5e614075b740f75/pyproject.toml#L81) and report them to GitHub (hoping they'll solve it).

Unfortunately, this is fragile and can break code if GitHub suddenly decides to pop-up nullable fields in its API response. For example, this was working well some days ago:

```py
from githubkit import GitHub
github = GitHub()
r = github.rest.orgs.get("frankie567-test-org-renamed")
r.parsed_data
```

But not anymore:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/fvoron/Development/githubkit/githubkit/response.py", line 50, in parsed_data
>     return parse_raw_as(self._data_model, self._response.content)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pydantic/tools.py", line 82, in pydantic.tools.parse_raw_as
>   File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 2 validation errors for ParsingModel[OrganizationFull]
> __root__ -> name
>   none is not an allowed value (type=type_error.none.not_allowed)
> __root__ -> blog
>   none is not an allowed value (type=type_error.none.not_allowed)

---

That's why I was wondering if we could tweak the `Missing` type so it implicitly allows `None`. So basically this part:

https://github.com/yanyongyu/githubkit/blob/fd80590ffd0efbed97398421f5e614075b740f75/githubkit/utils.py#L42

becomes:

```py
Missing: TypeAlias = Union[Literal[UNSET], T, None]
```

Admittedly, this is not perfectly accurate regarding the schema but it seems more bullet-proof while GitHub make up their mind about this.

**Comment by yanyongyu** [comment]
The `Missing` type is designed for field not exist in the data not only for API response but also for the request schema. Modifying this type may affect the entire behavior.

GitHub API may return None due to permission issues or some other server-side errors. The `parsed_data` is fully validated and designed to provide complete type hints to avoid programing errors that caused by type errors. If you do not need such feature, `response.json()` is also available for accessing the raw response data.

**Comment by frankie567** [comment]
Thank you for your answer, but that's not exactly my point. Validation is useful and desired, of course.

The thing is, GitHub schema is not really reliable regarding nullable or missing fields, as witnessed by the long list of overrides you maintain: https://github.com/yanyongyu/githubkit/blob/fd80590ffd0efbed97398421f5e614075b740f75/pyproject.toml#L105-L205

**Comment by yanyongyu** [comment]
There are indeed many inaccuracies in the rest api description file. `UNSET` and `None` are both falsy value, changing this type may have little impact programmingly (like if boolean condition). PR welcome :).  
But for me, I am more inclined to correct the schema to ensure that the validation is performed correctly.

For this example (https://api.github.com/orgs/frankie567-test-org-renamed), it is caused by the errors in github's schema. The `name` and `blog` can be unset but the schema provides type string. I have submitted many issues to the description repo :joy:.

**Comment by yanyongyu** [comment]
From https://github.com/github/rest-api-description#contributing

> This repository is automatically kept up to date with the description used to validate GitHub API requests as well as powering contract tests.

😟
